pact-foundation/pact-go

README.md, doc.go, dsl/broker.go, dsl/broker_test.go, dsl/mock_service.go, dsl/mock_service_test.go, dsl/pact.go, dsl/pact_test.go, dsl/publish.go, dsl/publish_test.go, types/publish_request.go, types/verify_request.go
Added new fields `BrokerURL` and `Tags` to the `pact.Verify()` function.
If `BrokerURL` is provided, pact will explore a Pact Broker and find all of the latest versions of any consumers (using HAL to navigate). This alleviates the need to explicitly pass in `PactURLs` and is more flexible as more consumers come on board.
Additionally, if `Tags` is provided, Pact will find all of the latest consumers by each Tag. This is useful when using [Matrix based testing](http://rea.tech/enter-the-pact-matrix-or-how-to-decouple-the-release-cycles-of-your-microservices/).
=> Ability to verify pacts from a broker and optionally given tags

README.md
Hi,
it seems to me, that these lines of code are an artefact and should be removed. Is that right? I've been confused by these, because they aren't necessary.
Cheers
=> [docs] Remove 4 lines of code from an example

dsl/pact.go, dsl/pact_test.go
I believe this closes #24, but I haven't been yet able to run the smoke tests, because of missing configuration.
=> fix(verify) prevent crash when calling VerifyProvider()

dsl/pact.go, dsl/pact_integration_test.go
Modify E2E tests so that consumer and provider don't use the same Pact struct, which is a more likely scenario.
=> fix(verify): fix sloppy nil pointer dereference in 33a04342 for #24

daemon/verification_service.go, dsl/pact_integration_test.go, dsl/pact_test.go, scripts/package.sh, types/verify_request.go
Adds support for a new feature of the broker - the ability to send provider verification results back to the Broker, allowing more intelligent CI practices.
The main use case this solves is allowing you (probably via a CI / CD processe) to detect Consumer changes that have not yet been verified by a provider. Publishing the status to the broker allows tooling to then query this status, and block a deployment if the contract has changed or has not been verified since last published.
See https://github.com/realestate-com-au/pact/blob/master/CHANGELOG.md#1110-8-may-2017 for more.
**Commit Details**:
- Upgrade to latest verifier (v1.0.1)
- Add new flags to verifier to allow results to be published
to a Pact Broker
=> feat(verification): publish verification results to broker

README.md
#34 Another update to the docs for correction. I added the correction to the Publisher function as illustrated in `pact_integration_test.go`
=> chore(docs): pact publisher Publish documentation correction

README.md
At GitHub project folder, it is redirecting to https://github.com/pact-foundation/pact-go/blob/master/docs.pact.io/roadmap.
=> Typo for Roadmap link

daemon/daemon.go, daemon/mock_service.go, daemon/mock_service_test.go, daemon/service.go, daemon/service_mock.go, daemon/verification_service.go, daemon/verification_service_test.go, dsl/client.go, dsl/client_test.go, dsl/pact.go, dsl/pact_test.go, utils/port.go, utils/port_test.go
In order to be friendsly with Docker and exposing ports on containers
the Pact struct will have an optional field for mock service ports.
The default action is to use the exact same function to find a free
port. But if the field `AllowedMockServicePorts` is passed then it will
limit the ports to those specified
=> DSL Controls Mock Servers Port

daemon/daemon.go, daemon/daemon_test.go, daemon/mock_service.go, daemon/service.go, daemon/service_manager.go, daemon/service_mock.go, daemon/service_test.go, daemon/verification_service.go, doc.go, dsl/client.go, dsl/client_test.go, dsl/pact.go, dsl/pact_test.go, examples/gin/provider/user_service_test.go, examples/go-kit/provider/user_service_test.go, examples/mux/provider/user_service_test.go, scripts/build_standalone_packages.sh, types/provider_verifier_response.go, types/verify_request.go
This enables you to write your provider verification tests like this:
``` golang
res, err := pact.VerifyProvider(types.VerifyRequest{
ProviderBaseURL: "baseurl",
PactURLs:        []string{"url1.json","url2.json"},
})
if err != nil {
t.Fatal(err)
}
for _, ex := range res.Examples {
if ex.Status != "passed" {
t.Errorf("%s\n%s\n", ex.FullDescription, ex.Exception.Message)
}
}
```
The main change is to `func (p PactClient) VerifyProvider(request types.VerifyRequest, reply *types.ProviderVerifierResponse) error`. The reply type is specific to the JSON output of the `pact-provider-verifier` binary. Also, I've changed the semantics of the error a bit. If a valid JSON response from the binary can be parsed, there will be no error. Otherwise, there will be an error, and it will include both stderr …
=> Add better provider verification output

README.md, doc.go, dsl/mock_service.go, dsl/pact.go
To point to links in pact-foundation/pact-ruby/wiki/
=> Fix broken links to realestate-com-au/pact/wiki

dsl/publish.go, dsl/publish_test.go
Add SetClient func to allow dsl users to control aspects of requests to the
Broker API, such as timeouts, headers, and Transport.
=> feat(publisher): add SetClient func

dsl/client.go, dsl/client_test.go, dsl/pact.go, dsl/pact_test.go
CI servers are sometimes under pressure... This PR adds an option to setup the maximum duration before timing-out waiting for Pact CLI (or provider server) to startup.
=> feat(client) allow customization of client timeout

dsl/client.go, dsl/client_test.go
Currently, when verifying that the provider is alive pact-go uses the pactClient's address https://github.com/pact-foundation/pact-go/blob/c2dcd782ab0bb3ee4a6a689ba0c4083f31258628/dsl/client.go#L125.
When attempting to run a pact-go test against a provider that isn't running on localhost you currently see the following error:
```
[ERROR] Expected server to start < 10s. Timed out waiting for Provider API to start on port 8000 - are you sure it's running?
```
This is because pactClient's address is not based on the provider base URL. This PR fixes the issue by attempting to establish a connection using the host from the ProviderBaseURL, similarly to how the port is established.
=> use the ProviderBaseURL's host when verifying the provider is alive 🐛

install/installer.go, install/installer_test.go
`GetVersionForBinary` assumes that only one line will be printed to stdout. If for any reason more than one line is printed to stdout `GetVersionForBinary` will fail. 
Make `GetVersionForBinary` assume that only the last line printed to stdout contains the version number.
=> fix(version check): Only parse the last line on stdout when checking version of cli tools

dsl/matcher.go, dsl/matcher_test.go
Return raw generated value for Mather's GetValue to be able to use the expected value for message metadata in VerifyMessageConsumer, e.g.
```
handler.Invoke(
&MyMessageContext{MyField: m.Metadata["my-field"].GetValue()},
*m.Content.(*Payload),
)
```
Closes #95
=> feat(get-value): implement GetValue in Matcher. Closes #95

dsl/matcher.go, dsl/matcher_test.go
Now that Like accepts an `interface{}` and the results get serialized into JSON, there's no need for these extra quotes.
=> removed extra quotes from string Like match

examples/go-kit/provider/transport.go
The `ErrNotFound` was repeated twice, fix that.
=> remove duplicated switch case

dsl/matcher.go, dsl/matcher_test.go, dsl/request.go
This PR includes three commits:
- 633eb1f, switches to typed matchers for Like, EachLike, Term; changes the type of certain API parameters from Matcher struct to StringMatcher interface
**This is the core of the change**
- c4d672d, removes the Type field from matcher structs and injects it only for marshaling to JSON.
The Type field isn't needed in go because of static typing, moreover, if any caller changes the value of the Type field it would likely cause incorrect behavior
Note that tests had to be updated because the order of the corresponding `json_class` property in JSON changed. This is generally inconsequential in JSON but the current tests specify a strict order of JSON properties. Alternatively the tests could be written in a more permissible way without enforcing the order or …
=> feat(api): use static types for matchers

CONTRIBUTING.md, README.md
Tripped over this while running through the example. Just looks like a bad paste.
Have also added the error checking after `NewRequest` as is in the real example code.
Signed-off-by: Brendan Devenney <brendan.devenney@cloudreach.com>
=> fix(docs) Fix code examples, update E2E test steps

dsl/pact.go
`verifify` -> `verify`
Not sure if `chore` was the right change type for this, apologies if it should be something else!
=> chore: fix typo for no pacts error

dsl/client.go
Use a stderr scanner instead of a stdout scanner to capture texts on stderr.  This change fixes an incorrect output and sometimes a data race.
=> fix: use stderr scanner on captureing stderr

dsl/matcher.go, dsl/matcher_test.go
=> fix: handle JSON tags correctly

dsl/matcher.go
This is a performance improvement.
We do not need to recompile regexes that match `regex=` and `example=` inside `pact` struct tags. I moved them into package-level vars.
=> chore: avoid recompiling struct tag matching regexes

dsl/client.go
by default, `Scanner.Scan()` halts for lines larger than [MaxScanTokenSize](https://golang.org/pkg/bufio/#pkg-constants) (64kb). if a JSON document in pact's output is larger than this, scanning stops and stdout contents are discarded
this change allocates a 64kb buffer up front, but grows the buffer up to 64mb for larger output
=> fix: increase max size of pact output buffer

README.md
The compiler return a `missing return` error in this README code example:
```go
// Pass in test case. This is the component that makes the external HTTP call
var test = func() (err error) {
u := fmt.Sprintf("http://localhost:%d/foobar", pact.Server.Port)
req, err := http.NewRequest("GET", u, strings.NewReader(`{"name":"billy"}`))
if err != nil {
return err
}
// NOTE: by default, request bodies are expected to be sent with a Content-Type
// of application/json. If you don't explicitly set the content-type, you
// will get a mismatch during Verification.
req.Header.Set("Content-Type", "application/json")
req.Header.Set("Authorization", "Bearer 1234")
if _, err = http.DefaultClient.Do(req); err != nil {
return err
}
}
```
Just added a `return` after the last `if`. Also omitted return values, …
=> feat: add missing return to README example

dsl/client.go, dsl/client_test.go
see issue https://github.com/pact-foundation/pact-go/issues/169
=> fix: handle verification response correctly

types/consumer_version_selector.go, types/consumer_version_selector_test.go
This PR adds support for new consumer version selectors.
- #172
=> Added consumer version selectors

dsl/matcher.go, dsl/matcher_test.go
Some of our DTO objects include unexported fields.
This small patch just ignores those fields, as they aren't serialized by the JSON encoder. This means they shouldn't form part of the API contract. And they can even cause `panics` if they include types that can't be handled.
Although I ran into this issue while experimenting with GRPC + Pact, I think this fix makes sense outside of this context as well. Any manually-written object might also have non-exported fields that shouldn't be part of the API Contract, while still ideally being supported by `dsl.Match`.
Note: these details probably aren't needed. This gets into the complications of my experiments with GRPC + Pact. But I wanted to include it for completeness.
I received this panic when creating the consumer pact:
```
2022-02-08 …
```
=> Match should skip unexported fields as they won't be serialized

CODE_OF_CONDUCT.md, dsl/matcher_test.go
update deprecated email address
=> docs: update pact-support@googlegroups.com to pact-foundation

README.md
A small change to fix some minor syntax issues in the readme.
=> Fix syntax issues in readme

installer/installer.go
causes error such as: 
`2022/08/25 16:18:11 [ERROR] Your Pact library installation is out of date and we were unable to download a newer one for you: open /Users/me/.pact/pact-go.yml: permission denied`
=> fix HOME/.pact dir permission

provider/verify_request.go, provider/verify_request_test.go
Proposed interim support for provider webhook verification.   See https://github.com/pact-foundation/pact-reference/issues/250
=> feature: add pact_url env variable to VerifiyRequest configuration

internal/native/message_server.go, message/v4/asynchronous_message.go, message/v4/synchronous_message.go
This ensures V4 asynchronous and synchronous messages have the correct specification version applied to them.
=> fix: set specification version on v4 message types

internal/native/message_server.go
=> fix: remove relative numeric size for message contents c interface

.github/workflows/golangci-lint.yml, .github/workflows/test.yml
- Updates golanglint-ci such that it now passes.
- Targets v1.x.x branch and v1* release tags, rather than main/master which is now for v2
- Updates other actions tags (checkout and setup-go) to latest
Notes: Appveyor build has failed for circa three years, so will be looked at in a separate PR
=> ci(deps): update golangci-lint ci build to pass on v1.x.x branch

Dockerfile, docker-compose.yml
- Use the latest pactfoundation/pact-broker
- Use the `latest-multi` image to help those out on arm64
- Adds a healthcheck to ensure everything is sweet when starting up
- Update pact-ruby-standalone in docker image to latest
=> chore: update pactfoundation/pact-broker over dius broker

.github/workflows/release.yml, .github/workflows/test.yml
Relates to #312 
- Adds go 1.20 as latest supported version for testing
- Uses go 1.20 for release
- Adds notes around EOL versions
There is a note in the readme around go versions
> NOTE: If using Go 1.19 or later, you need to run go install instead 
> go install github.com/pact-foundation/pact-go/v2@2.x.x
It would be worth adding a nice compat/support table, and I've not we don't have a supported platform/arch list
Similar to 
**OS/Arch support**
| OS | AMD 64 | arm |
|----|---------|-----|
| Linux (glibc) | ✅  | ✅  |
| Mac | ✅  | ✅  |
| Windows | ✅  | ❌   |
| Linux (alpine) | 🔸 | 🔸 |
✅ = installs without build hooks, pre-built native library
🔸 = works, however, requires build hooks / runtime compilation or installation
❌ = not supported
from here …
=> chore(ci): test/release on go 1.20

.github/workflows/test.yml, Makefile, examples/avro/avro_consumer_test.go, examples/avro/avro_provider_test.go, examples/avro/codec.go, examples/avro/user.avsc, examples/avro/user.go, go.mod, go.sum
Build will fail until https://github.com/austek/pact-avro-plugin/issues/19 is addressed.
=> feat: add an Avro example

.cirrus.yml, .github/workflows/golangci-lint.yml, .github/workflows/test.yml, Dockerfile, Makefile, README.md, docker-compose.yml, scripts/pact.ps1
as per #290 but retargeted against v1.x.x branch
_____
PR's to Travelling ruby to update the supported archs
- https://github.com/phusion/traveling-ruby/pull/132
- https://github.com/phusion/traveling-ruby/pull/133
Which means we can now support
| OS     | Ruby      | Architecture | Supported |
| -------| ------- | ------------ | --------- |
| OSX    | 3.2.2     | x86_64       | ✅         |
| OSX    | 3.2.2     | aarch64 (arm)| ✅         |
| Linux  | 3.2.2   | x86_64       | ✅         |
| Linux  | 3.2.2   | aarch64 (arm)| ✅          |
| Windows| 3.2.2 | x86_64       | ✅        |
| Windows| 3.2.2 | x86       | ✅        |
| Windows| 3.2.2 | aarch64 (via x86 emulation) |  ✅        |
- https://github.com/pact-foundation/pact-ruby-standalone/pull/100
- …
=> Update pact-go v1 to use latest pact-ruby-standalone (ruby 3.2 + arm64 support)

dsl/pact.go, proxy/http.go, proxy/http_test.go
Acquire the port in VerifyMessageProvider and VerifyProvider atomically by using the same listener for starting the HTTP server that was used for a free port acquisition.
This prevents a race condition when multiple pact verifiers run in parallel and compete for free ports, which could result in errors like
```
Expected server to start < 10s. Timed out waiting for http verification proxy on port 34425 - check for errors
```
=> fix(verifier): acquire HTTP port atomically

installer/installer.go, installer/installer_test.go
Addresses #345
Tested by running the install command with and without --libDir.
Verified that my project's pact test compile and run correctly after installing libpact_ffi.dylib via a freshly built `pact-go`.
Verified otool output matches full path.
E.g.
```
~/github/pact-go install-name-tool ≡
15:05:16 🐠 
build/pact-go -l DEBUG install --libDir /tmp/
2023/10/02 15:05:18 [INFO] set lib dir target to /tmp/
2023/10/02 15:05:18 [INFO] package libpact_ffi not found
2023/10/02 15:05:18 [INFO] downloading library from https://github.com/pact-foundation/pact-reference/releases/download/libpact_ffi-v0.4.5/libpact_ffi-osx-x86_64.dylib.gz to /tmp/libpact_ffi.dylib
&{}
2023/10/02 15:05:19 [DEBUG] obtaining hash for file /tmp/libpact_ffi.dylib
2023/10/02 15:05:19 [DEBUG] writing config …
```
=> fix: set install_name to absolute path for libpact_ffi.dylib (#345)

examples/provider_test.go, internal/native/verifier.go, provider/verify_request.go
Addresses https://github.com/pact-foundation/pact-go/issues/340
=> No color output

.github/workflows/update-ffi.yml, scripts/create-pr-to-update-pact-ffi.sh, scripts/dispatch-ffi-released.sh
Aim:- Provide a CI workflow, that can be triggered on release of the Pact FFI library.
Relates to https://github.com/pact-foundation/pact-reference/issues/375 , specifically `Trigger dependant client libraries workflows to raise PR's`
This change borrows from the existing update workflow on release of the pact-ruby-standalone.
- release trigger 
- https://github.com/pact-foundation/pact-ruby-standalone/blob/3cecd6dce82922697f1ba2a3ccdabdaebdb54be9/.github/workflows/release.yml#L46-L63
1. Release point in Pact-reference project 
1.  https://github.com/pact-foundation/pact-reference/blob/fc33ad23e78698ecf1fb55eedb7dc228f96def17/.github/workflows/release.yml#L74-L81
1. Example Release
1. https://github.com/pact-foundation/pact-reference/releases/tag/libpact_ffi-v0.4.14 
Our ci workflow for …
=> ci: add workflow to update on pact-ffi-released events

installer/installer.go, installer/installer_test.go
Not sure if you want this in, but I was using pact on Windows and there the default path "user/local/lib" is most likely never right. I am using TDM GCC which is installed at `C:\TDM-GCC-64\bin`.
With the powershell `Get-Command` it is possible to detect the install path and put the library in there directly which is a better default on Windows I guess since otherwsie one would set this path manually.
=> Add function to expose the NativeLibPath

types/publish_request.go
Small change to pact v1.x to support publishing pacts with branches.
I was updating the pact-go-workshop and wanted to get it to the latest of pact-go v1, with the supported workflow of branches over tags, and recording deployments, over using tags for environments, before migrating over to pact-go v2.
Tested locally
```
🕙12:57:56 ❯ make publish
--- 📝 Publishing Pacts
go run consumer/client/pact/publish.go
Publishing Pact files to broker /Users/yousaf.nabi/dev/pact-foundation/pact-workshop-go/pacts test.pactflow.io
2024/01/19 12:58:33 [INFO] Updated GoAdminService version 1.0.0 with branch master
2024/01/19 12:58:33 [INFO] Pact successfully republished for GoAdminService version 1.0.0 and provider GoUserService with no content changes.
2024/01/19 12:58:33 [INFO]   View the published pact …
```
=> feat: support publish pacts with branch for v1.x

internal/native/mock_server.go
Use the same definition for `pactffi_given` and `pactffi_given_with_param`
As described in this issue (https://github.com/golang/go/issues/67670#issuecomment-2137716522), 
duplicated but inconsistent definition in `pact-go/internal/native/mock_server.go`, `pact-go/internal/native/message_server.go` causes the problem.
Closes #402
=> fix: use the same signature for the same function (#402)

client/service.go, client/service_manager.go, client/service_test.go, dsl/client.go, dsl/client_test.go, dsl/pact.go, dsl/publish.go, dsl/service_mock.go
Adding ability to specify path to Pact CLI for systems where the CLI can't easily be installed
=> Pact CLI Install Path

README.md
Adding the missing first param on the V2HTTPMockProvider.ExecuteTest() call it should be t (*testing.T)
=> Adding Missing Param in Consumer test docs

.github/workflows/golangci-lint.yml, .github/workflows/test.yml, Makefile, consumer/http_v4_test.go, examples/avro/avro_consumer_test.go, examples/grpc/grpc_consumer_test.go, examples/plugin/consumer_plugin_test.go, examples/protobuf-message/protobuf_consumer_test.go, installer/installer.go, internal/native/message_server_test.go, internal/native/mock_server_test.go, message/v4/asynchronous_message_test.go, message/v4/synchronous_message_test.go, scripts/install-cli.sh
- updates libpact_ffi to 0.4.21
- updates all plugin deps to latest versions
- update ci action deps to avoid deprecation warnings
- test on latest supported golang version (1.22.x)
note: fail fast due to sporadic seg faults
=> Fix/update pact ffi 0.4.21

README.md, installer/installer.go, installer/installer_test.go
See release notes
https://github.com/pact-foundation/pact-reference/releases/tag/libpact_ffi-v0.4.21
=> fix: rename macos binaries due to naming change in v0.4.21 libpact_ffi

internal/native/message_server.go, internal/native/mock_server.go, internal/native/signal.go, internal/native/verifier.go
fixes #269 
yak shave and a half, bit of a write up and repro in the pact reference repo
https://github.com/pact-foundation/pact-reference/compare/master...YOU54F:pact-reference:issue/go_signals
tried building the ffi and csv plugin with musl 1.25, as 1.24 has a fix in it, similar to that referenced by Jason in the original issue for glibc.
that didnt seem to solve the issue for me
we cant move to that new a version of glibc as we need to be compatible with older distroes, and i haven’t tested that out to see if it works.
some links from the yak shave
cgo onstack failures 
- https://github.com/wailsapp/wails/pull/2152/files#diff-d4a0fa73df7b0ab971e550f95249e358b634836e925ace96f7400480916ac09e
- https://github.com/golang/go/issues/51787
- https://www.openwall.com/lists/musl/2020/08/09/1
- …
=> fix: plugin verification panics due to missing SA_ONSTACK signal

internal/native/message_server.go, internal/native/mock_server.go
After splitting out a large PR of changes to apply #432 - I noted that I had previously applied the installed signal handlers, after the ffi framework has started the plugins.
Due to this, we are still encountering the issues in the project. Here is one on the mock server side
```
2024-07-03T20:13:07.907144Z DEBUG ThreadId(01) pact_models::pact: Writing new pact file to "/home/runner/work/pact-go/pact-go/examples/protobuf-message/../pacts/protobufmessageconsumer-protobufmessageprovider.json"
signal 17 received but handler not on signal stack
mp.gsignal stack [0xc000008000 0xc000010000], mp.g0 stack [0x7ffc7df38600 0x7ffc7ef37610], sp=0xc0000db398
fatal error: non-Go code set up signal handler without SA_ONSTACK flag
```
I actually wonder if on the verifier side, we will catch it in the …
=> fix: install signal handlers should occur after plugins started

consumer/http.go, internal/native/message_server.go, internal/native/message_server_test.go, internal/native/mock_server.go, internal/native/mock_server_test.go, message/v4/asynchronous_message.go, message/v4/synchronous_message.go, provider/verify_request.go
If I run the test suite with `make test` - I get zombie plugin processes left in my shell
```
PID TTY           TIME CMD
1537 ttys001    0:01.26 /bin/zsh -il
1770 ttys002    0:00.03 login -fp saf
1772 ttys002    0:00.43 -zsh
29027 ttys007    0:00.61 /bin/zsh -il
12917 ttys014    0:00.15 /Users/saf/.pact/plugins/protobuf-0.3.15/pact-protobuf-plugin
13757 ttys014    0:00.00 /Users/saf/.pact/plugins/csv-0.0.6/pact-csv-plugin
13797 ttys014    0:00.26 /Users/saf/.pact/plugins/protobuf-0.3.15/pact-protobuf-plugin
14159 ttys014    0:00.00 ps -a
50964 ttys014    0:02.13 /bin/zsh -il
```
After this fix, everything still passes, and I don't have any zombie processes
```
PID TTY           TIME CMD
1537 ttys001    0:01.26 /bin/zsh -il
1770 ttys002    0:00.03 login -fp saf
1772 ttys002    0:00.43 -zsh …
```
=> fix: zombie plugin processes

.github/workflows/test.yml, Dockerfile, Makefile, docker-compose.yml
- Updates Dockerfile
- Dockerfile was relevant for pact-go v1, now updated and tested as part of CI
- Inability to use Docker in MacOS / Windows, means to run Pact Broker based tests, we need to use a hosted broker. This poses challenges for external contributors and the sharing of secrets, as using shared credentials in plain-text although convenient for our demo env, isn't best practise for actual end user use.
- Provide a `make pact_local` command that skips publishing of pacts, and via setting `SKIP_PUBLISH` controls the provider verification test to either run a local or pact broker based verification. The publish code path is still covered by the linux runner. (there is probably a more elegant way of conditionally setting the values rather than a large if / else block
=> chore(ci): test Docker images in CI

README.md
maybe worth adding this link in too
https://github.com/go101/go101/wiki/CGO-Environment-Setup
=> docs: Add cgo pre-reqs and tips for macos/windows

internal/native/message_server.go, internal/native/mock_server.go
These changes fixes a crash in tests when using `WithCompleteRequest() or `WithCompleteResponse()` with multiple headers.
```
unexpected fault address 0x1d4c860
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1d4c860 pc=0x4a28fd]
goroutine 14 gp=0xc0003c28c0 m=3 mp=0xc00009d008 [running]:
runtime.throw({0x1e99d7e?, 0xc000111f80?})
GOROOT/src/runtime/panic.go:1023 +0x5c fp=0xc0000eb660 sp=0xc0000eb630 pc=0x46cd7c
runtime.sigpanic()
GOROOT/src/runtime/signal_unix.go:895 +0x285 fp=0xc0000eb6c0 sp=0xc0000eb660 pc=0x487265
runtime/internal/atomic.casPointer(0x1d4c860?, 0x46c765?, 0x46b700?)
GOROOT/src/runtime/atomic_pointer.go:63 +0x3d fp=0xc0000eb6e0 sp=0xc0000eb6c0 pc=0x4a28fd
runtime/internal/atomic.(*UnsafePointer).CompareAndSwap(...) …
```
=> fix: don't use defer in a loop

.github/workflows/test.yml, Makefile, consumer/http_v4_test.go, examples/avro/avro_consumer_test.go, examples/avro/avro_provider_test.go, examples/grpc/grpc_consumer_test.go, examples/protobuf-message/protobuf_consumer_test.go, internal/native/c_types_unix.go, internal/native/c_types_win.go, internal/native/message_server.go, internal/native/message_server_test.go, internal/native/mock_server.go, internal/native/mock_server_test.go, message/v4/asynchronous_message_test.go, message/v4/synchronous_message_test.go, scripts/build.ps1, scripts/examples_consumer.ps1, scripts/examples_provider.ps1, scripts/unit.ps1
- Added Windows x86_64 GitHub Action Runner
- gRPC tests for windows require backslashes escaping, or forward slashes in path to proto file. Can we cater for this in the pact-protobuf-plugin?
- Avro plugin tests are skipped on windows
- `avro` plugin fails to run at point of install time via `pact-plugin-cli`
- See https://github.com/pact-foundation/pact-plugins/issues/68
- ~all plugins fail to cleanly shutdown after execution, and they can only be closed externally via the task manager. This is causing tests to fail in GitHub actions.~ Fixed by https://github.com/pact-foundation/pact-plugins/pull/67
=> ci: add windows runners

internal/native/message_server.go, message/v4/synchronous_message.go, message/v4/synchronous_message_test.go
Metadata is not being included in a synchronous v4 message interaction, as the function we are calling does not know which part (request or response) that metadata is being attached to.
The output of the v4 sync message test, post this change now shows
```
{
"consumer": {
"name": "consumer"
},
"interactions": [
{
"description": "some description",
"pending": false,
"providerStates": [
{
"name": "some state"
}
],
"request": {
"contents": {
"content": {
"foo": "bar"
},
"contentType": "application/json",
"encoded": false
},
"metadata": {
"contentType": "application/json",
"meta_request": "meta_request_data"
}
},
"response": [
{
"contents": {
"content": {
"foo": "bar"
},
"contentType": "application/json",
"encoded": false
},
"metadata": {
"contentType": "application/json",
"meta_response": …
```
=> fix: ensure sync messages write metadata to both req & res

provider/verify_request.go
Improving documentation to ensure people avoid falling into the trap of having URLs without schema and a base path.
Issue found after [this discussion in Slack](https://pact-foundation.slack.com/archives/C9UTHTFFB/p1732207319028629)
=> Improving Provider VerifyRequest - ProviderBaseURL documentation.

.github/workflows/golangci-lint.yml, .github/workflows/test.yml, go.mod, installer/installer.go
go 1.21 is eol as of 13 Aug 2024 and go-grpc 1.68.0 requires 1.22
=> chore(deps)!: require minimum go version 1.22

consumer/http.go, message/v3/asynchronous_message.go, message/v4/asynchronous_message.go, message/v4/synchronous_message.go, provider/verifier.go
example metadata
```json
"metadata": {
"pact-go": {
"version": "2.1.0"
},
"pactRust": {
"ffi": "0.4.26",
"models": "1.2.7"
},
"pactSpecification": {
"version": "4.0"
}
}
```
Works as per pact-js
https://github.com/search?q=repo%3Apact-foundation%2Fpact-js%20this.pact.addMetadata&type=code
note, for pact-js, we may want to also write pact-js-core library version as well
noted when investigating #499
=> feat: add pact go client lib version to pact
